CREATE DATABASE faculdade;

USE faculdade;

CREATE TABLE usuarios (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
nome VARCHAR(90) NOT NULL,
sobrenome VARCHAR(90) NOT NULL,
email VARCHAR(120) NOT NULL UNIQUE,
curso VARCHAR(5) NOT NULL, -- 5 POR QUE VAMOS RECEBER A SIGLAS, O NOME QUE COLOCAMOS NO PHP.
nota_atividade DECIMAL (5,2) NOT NULL DEFAULT 0,
nota_prova DECIMAL (5,2) NOT NULL DEFAULT 0,
nota_final DECIMAL (5,2) NOT NULL DEFAULT 0
);

SELECT*FROM usuarios;

DELETE*FROM usuarios
WHERE nome = "camiola";